### ISSUE TITLE
怎么隐藏openapi key？？？

### ISSUE THREAD

**Issue by sunyuwen666** [sbaliyun/chatgpt-html#1]
[what.md](https://github.com/sbaliyun/chatgpt-html/files/10251905/what.md)

**Comment by sunyuwen666** [comment]
大佬大佬，该怎么隐藏key啊！

xhr.setRequestHeader("Authorization", "Bearer sk-123456");？？？

**Comment by kof4467** [comment]
需要起一个后端服务包一层接口，把key隐藏到后端服务

**Comment by lxh514618** [comment]
请问下key怎么填

**Comment by sunyuwen666** [comment]
太难了，前端新手属实不会啊。。。



在 2022-12-19 14:22:21，"kof4467" ***@***.***> 写道：

需要起一个后端服务包一层接口，把key隐藏到后端服务

**Comment by sunyuwen666** [comment]
index.html第47行修改sk-123456为你的key



在 2022-12-24 15:09:23，"lxh514618" ***@***.***> 写道：

请问下key怎么填

**Comment by QingJ01** [comment]
不用，你加密js就可以了，然后做一下防开发者工具

**Comment by sbaliyun** [comment]
随便用一个后端反向代理下就可以了  
暂时没打算开源自己写的后端代理(因为太low了 拿出去太丢人了)
