### ISSUE TITLE
网信办出手了？

### ISSUE THREAD

**Issue by sowhat233** [sbaliyun/chatgpt-html#10]
如图
![3%D4CA4({0S X8Y)W`}%J4C](https://user-images.githubusercontent.com/36954787/219313024-7d599945-4f2c-4316-95f8-77654204f1ee.png)
请问是真是假？

**Comment by sbaliyun** [comment]
真的 域名和服务器都被封了 警察找了我两次了

**Comment by sowhat233** [comment]
咦，那你这个 https://www.cveoy.com
还能打得开呀
意思是你那个sbaliyun.com是备案 所以才被监管的？

**Comment by sbaliyun** [comment]
https://hostloc.com/thread-1138238-1-1.html

**Comment by sowhat233** [comment]
> https://hostloc.com/thread-1138238-1-1.html

老哥你这是啥？

**Comment by sbaliyun** [comment]
由于涉及政治问题 sbaliyun.com 已被中国政府相关部门永久封禁
新域名为https://www.cveoy.com/
