### ISSUE TITLE
用的是GPT3还是GPT-3.5-TURBO?

### ISSUE THREAD

**Issue by joshatt** [sbaliyun/chatgpt-html#15]
直接问AI的话，回答是GPT3。。。。我试了很多分享出来的网页版，都回答是3.  而且似乎退步了，记得十几天前在官网回答比较详尽，现在连官网的回答都简短了？

**Comment by sbaliyun** [comment]
GPT-3.5-TURBO

**Comment by ydqsbfsyi** [comment]
> GPT-3.5-TURBO

谢谢
