### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by sbwgg** [sbaliyun/chatgpt-html#2]
rvthub.com/:1 Access to XMLHttpRequest at 'https://cc-api.sbaliyun.com/' from origin 'https://rvthub.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
(index):89          POST https://cc-api.sbaliyun.com/ net::ERR_FAILED

**Comment by jugla44** [comment]
rvthub.com/:1 Access to XMLHttpRequest at 'https://cc-api.sbaliyun.com/' from origin 'https://rvthub.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
(index):89          POST https://cc-api.sbaliyun.com/ net::ERR_FAILED
