### ISSUE TITLE
api.openai.com/v1/completions 是 ChatGPT 的 API 接口吗？

### ISSUE THREAD

**Issue by GWDx** [sbaliyun/chatgpt-html#4]
[API Reference - OpenAI](https://beta.openai.com/docs/api-reference/introduction) 上有这个 API，但没有提到 ChatGPT，这个可能是普通的 GPT-3 的 API，而不是 ChatGPT 的。

**Comment by sbaliyun** [comment]
ChatGPT 目前没有任何API接口
