### ISSUE TITLE
运行之后，结果：正在思考，请等待...... 

### ISSUE THREAD

**Issue by cn0068** [sbaliyun/chatgpt-html#5]
宝塔部署的，
clone: from https://github.com/sbaliyun/chatgpt-html.git
已经替换了有效的api key
xhr.setRequestHeader("Authorization", "Bearer 有效的api key");
运行之后，结果：正在思考，请等待...... 、
一直停留在这里，没有出结果。请问可能原因 是什么 ？

**Comment by coderdream** [comment]
官网也有同样的问题，估计大陆的IP已经不能访问了
![image](https://user-images.githubusercontent.com/1549511/217122210-066a14f8-45b5-43d1-a1e9-353128951749.png)

**Comment by vicaelae** [comment]
我也遇到了一样的问题，美国机器
![image](https://user-images.githubusercontent.com/114346243/217233003-0f531289-ae9b-4ca2-be8c-334eb1c19ece.png)

**Comment by vicaelae** [comment]
我也遇到了一样的问题，美国机器
![image](https://user-images.githubusercontent.com/114346243/217233003-0f531289-ae9b-4ca2-be8c-334eb1c19ece.png)

**Comment by realzsy** [comment]
我也是这样报错

**Comment by llj1998** [comment]
我也是，网络与key都没问题，但却不能用，但作者的网站竟然能用

**Comment by vicaelae** [comment]
作者似乎被约谈了，都换域名了

**Comment by sbaliyun** [comment]
新域名 https://www.cveoy.com/
